2.3.0 bottles
handle Framework installation
let kr handle plist

diff --git a/kr b/kr
--- a/kr
+++ b/kr
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION=2.2.7
+VERSION=2.3.0
 
 install_darwin() {
 	command -v brew &>/dev/null && test "$1" = "brew"
@@ -52,13 +52,11 @@ install_darwin_manual() {
 
 	MAJOR_MAC_VERSION=$(sw_vers -productVersion | awk -F '.' '{print $1 "." $2}')
 	case $MAJOR_MAC_VERSION in
-		10.10) OS_NAME=yosemite;   BOTTLE_HASH=c24d51df5cb1a775ed5e7250a2d59f953ae243e0956134092bad68008f47e9bc;;
-		10.11) OS_NAME=el_capitan; BOTTLE_HASH=fe4d321c85e81d3d40e677b049ef4deff6653155935547360993b9f14e2c80dd;;
-		10.12) OS_NAME=sierra;     BOTTLE_HASH=5c801201f7e718d7868189586da236ed2d853520f9447e1d3ab96e70976f125e;;
-
-		#	use 10.12 bottle for 10.13 until build dependencies are compilable on 10.13
-		10.13) OS_NAME=sierra;     BOTTLE_HASH=5c801201f7e718d7868189586da236ed2d853520f9447e1d3ab96e70976f125e;;
-		*) say "Unsupported OS X version $MAJOR_MAC_VERSION. Kryptonite requires 10.10+" && exit 1 ;;
+		#10.10 NO LONGER SUPPORTED
+		10.11) OS_NAME=el_capitan;	BOTTLE_HASH=ca97f72a0c0983269e3bcf6b2e838098ebf8ecb86291da0eee1f7f5a83860183;;
+		10.12) OS_NAME=sierra;     	BOTTLE_HASH=72552a17e9f4e0c16a1e383525ebe275d0ab072f057b34e2ebf5d67066a13303;;
+		10.13) OS_NAME=high_sierra;	BOTTLE_HASH=c8218c22345aea05fcc17cb763425462018033f6ec5478426c4c7564b9275619;;
+		*) say "Unsupported OS X version $MAJOR_MAC_VERSION. Kryptonite requires 10.11+" && exit 1 ;;
 	esac
 	say Downloading Kryptonite.
 	KR_FILE_PREFIX=kr-$VERSION.$OS_NAME
@@ -70,23 +68,15 @@ install_darwin_manual() {
 
 	ensure mk_owned_dir_if_not_exists $PREFIX/lib
 	ensure mk_owned_dir_if_not_exists $PREFIX/bin
-	ensure mk_owned_dir_if_not_exists $PREFIX/share/kr
+	ensure mk_owned_dir_if_not_exists $PREFIX/Frameworks
 
 	ignore rm -rf /tmp/kr
 	ensure tar xf /tmp/$KR_FILE_PREFIX.tar.gz -C /tmp/
 	ensure mv_maybe_sudo "/tmp/kr/$VERSION/bin/*" $PREFIX/bin/
 	ensure mv_maybe_sudo "/tmp/kr/$VERSION/lib/*" $PREFIX/lib/
-	ensure mv_maybe_sudo "/tmp/kr/$VERSION/share/kr/*" $PREFIX/share/kr/
+	ensure rmrf_maybe_sudo "$PREFIX/Frameworks/krbtle.framework"
+	ensure mv_maybe_sudo "/tmp/kr/$VERSION/Frameworks/krbtle.framework" $PREFIX/Frameworks/
 
-	ESCAPED_PREFIX=${PREFIX//\//\\\/}
-	perl -0777 -pi -e "s/\\@\\@HOMEBREW_PREFIX\\@\\@/$ESCAPED_PREFIX/" $PREFIX/share/kr/co.krypt.krd.plist
-	ensure mkdir -p ~/Library/LaunchAgents/
-	ensure cp $PREFIX/share/kr/co.krypt.krd.plist ~/Library/LaunchAgents/
-
-	ignore launchctl stop ~/Library/LaunchAgents/co.krypt.krd.plist &>/dev/null
-	ignore launchctl unload ~/Library/LaunchAgents/co.krypt.krd.plist &>/dev/null
-	ensure launchctl load ~/Library/LaunchAgents/co.krypt.krd.plist
-	
 	ensure mkdir -p ~/.ssh
 	ensure touch ~/.ssh/config
 	
@@ -201,6 +191,11 @@ is_my_dir() {
 #	$2 must be a directory, not the new file name
 mv_maybe_sudo() {
 	(is_my_dir $2 && ensure mv -f $1 $2) || ensure warn_sudo mv -f $1 $2
+}
+
+#	rm $1 using sudo if necessary, failing gracefully if not present
+rmrf_maybe_sudo() {
+	(is_my_dir `dirname $1` && ensure rm -rf $1) || ensure warn_sudo rm -rf $1
 }
 
 warn_sudo() {
